### ISSUE TITLE
Sometimes zookeeper fails and ingest job (& generally speaking RODA) does not handle properly the failure

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1132]
When executing an ingest job, and a failure occurs in Apache Solr and/or Apache Zookeeper during a step execution (i.e. executing a specific plugin), the plugin fails to do all its work because processing ends due to non check exception as shown in the following stack trace:

```java
2018-01-10 17:54:17,209 [JobsSystem-io-2-dispatcher-10150] ERROR o.r.c.plugins.plugins.PluginHelper - Unexpected exception during 'objectsLogic' execution
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://dc1srvdb:8983/solr/PreservationEvent: No registered leader was found after waiting for 4000ms , collection: 
PreservationEvent slice: shard1
        at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:577)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:372)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:325)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1121)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:891)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:827)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
        at org.apache.solr.client.solrj.SolrClient.deleteByQuery(SolrClient.java:895)
        at org.apache.solr.client.solrj.SolrClient.deleteByQuery(SolrClient.java:858)
        at org.roda.core.index.utils.SolrUtils.delete(SolrUtils.java:2784)
        at org.roda.core.index.IndexModelObserver.deleteDocumentsFromIndex(IndexModelObserver.java:879)
        at org.roda.core.index.IndexModelObserver.representationDeleted(IndexModelObserver.java:641)
        at org.roda.core.index.IndexModelObserver.representationUpdated(IndexModelObserver.java:632)
        at org.roda.core.model.ModelObservable.notifyRepresentationUpdated(ModelObservable.java:104)
        at org.roda.core.plugins.plugins.characterization.SiegfriedPlugin.executeOnAIP(SiegfriedPlugin.java:122)
        at org.roda.core.plugins.AbstractAIPComponentsPlugin$1.process(AbstractAIPComponentsPlugin.java:47)
        at org.roda.core.plugins.plugins.PluginHelper.processObjects(PluginHelper.java:132)
        at org.roda.core.plugins.AbstractAIPComponentsPlugin.execute(AbstractAIPComponentsPlugin.java:40)
        at org.roda.core.plugins.plugins.ingest.eupo.DefaultIngestPlugin.executePlugin(DefaultIngestPlugin.java:659)
        at org.roda.core.plugins.plugins.ingest.eupo.DefaultIngestPlugin.doFileFormatIdentification(DefaultIngestPlugin.java:622)
        at org.roda.core.plugins.plugins.ingest.eupo.DefaultIngestPlugin.execute(DefaultIngestPlugin.java:198)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:54)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:39)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

The solution:
1. Create two checked exceptions: one more generic called *ObserverException* and a second one more specific called *ModelObserverException*;
2. Ensure that, for the only ModelObserver available (*IndexModelObserver*), non checked exception *org.apache.solr.common.SolrException* is caught and a *ModelObserverException* is thrown;
3. Ensure that every single place in code that invokes ModelObserver methods handles that exception and, in ingest specific tasks, job execution for that AIP ends right there with a failure.

**Comment by nunovieira220** [comment]
It is done but a proper review is needed due to important changes.

**Comment by hsilva-keep** [comment]
Review done.
