### ISSUE TITLE
File notification fails to index because recipientUsers is a required field

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1210]
```
roda_1   | 2018-04-27 09:31:56,062 [JobsSystem-io-2-dispatcher-39] ERROR o.a.solr.handler.RequestHandlerBase - org.apache.solr.common.SolrException: [doc=342dd778-5bc0-4e62-b717-6f30c056a06a] missing required field: recipientUsers
roda_1   | 	at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:197)
roda_1   | 	at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:82)
roda_1   | 	at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:280)
roda_1   | 	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:214)
roda_1   | 	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:169)
roda_1   | 	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:68)
roda_1   | 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:48)
roda_1   | 	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:934)
roda_1   | 	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1089)
roda_1   | 	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:712)
roda_1   | 	at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:250)
roda_1   | 	at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:177)
roda_1   | 	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:94)
roda_1   | 	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:69)
roda_1   | 	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
roda_1   | 	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2102)
roda_1   | 	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:178)
roda_1   | 	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
roda_1   | 	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:173)
roda_1   | 	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:138)
roda_1   | 	at org.roda.core.index.utils.SolrUtils.create(SolrUtils.java:1195)
roda_1   | 	at org.roda.core.index.utils.SolrUtils.create(SolrUtils.java:1232)
roda_1   | 	at org.roda.core.index.IndexModelObserver.addDocumentToIndex(IndexModelObserver.java:920)
roda_1   | 	at org.roda.core.index.IndexModelObserver.addDocumentToIndex(IndexModelObserver.java:915)
roda_1   | 	at org.roda.core.index.IndexModelObserver.notificationCreatedOrUpdated(IndexModelObserver.java:1125)
roda_1   | 	at org.roda.core.model.ModelObservable.lambda$notifyNotificationCreatedOrUpdated$40(ModelObservable.java:237)
roda_1   | 	at org.roda.core.model.ModelObservable.notifyObserversSafely(ModelObservable.java:58)
roda_1   | 	at org.roda.core.model.ModelObservable.notifyNotificationCreatedOrUpdated(ModelObservable.java:237)
roda_1   | 	at org.roda.core.model.ModelService.createNotification(ModelService.java:2206)
roda_1   | 	at org.roda.core.plugins.external.uminho.UminhoDefaultIngestPlugin.sendNotification(UminhoDefaultIngestPlugin.java:480)
roda_1   | 	at org.roda.core.plugins.external.uminho.UminhoDefaultIngestPlugin.afterAllExecute(UminhoDefaultIngestPlugin.java:322)
roda_1   | 	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginAfterAllExecuteIsReady(AkkaWorkerActor.java:71)
roda_1   | 	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:41)
roda_1   | 	at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:258)
roda_1   | 	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
roda_1   | 	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:147)
roda_1   | 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
roda_1   | 	at akka.actor.ActorCell.invoke(ActorCell.scala:559)
roda_1   | 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
roda_1   | 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
roda_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
roda_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
roda_1   | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by luis100** [comment]
Make recipientUsers field in Notification index schema optional, or define a static recipient (e.g. the file path) in the File Notification.

**Comment by luis100** [comment]
Actually the problem was due the `ingest.daily.file_endpoint` was not starting with `file:///`.
This should not be needed, as the option lives in a different property from the http notification, and therefore does not need the file protocol to differentiate.

Created #1214 to drop the file:// prefix.
