### ISSUE TITLE
Error when registering error transforming lites into objects

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1236]
```
2018-05-24 11:11:28,688 [JobsSystem-io-2-dispatcher-589] ERROR o.r.c.p.o.akka.AkkaWorkerActor - Error executing plugin.execute()
java.lang.ArrayIndexOutOfBoundsException: 1
        at org.roda.core.plugins.plugins.PluginHelper.transformLitesIntoObjects(PluginHelper.java:1233)
        at org.roda.core.plugins.plugins.PluginHelper.processObjects(PluginHelper.java:131)
        at org.roda.core.plugins.AbstractAIPComponentsPlugin.execute(AbstractAIPComponentsPlugin.java:40)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:54)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:39)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:258)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:147)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
        at akka.actor.ActorCell.invoke(ActorCell.scala:559)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by nunovieira220** [comment]
Done
