### ISSUE TITLE
Using Tika Feature extraction plugin puts ingest process in an unstable state

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1297]
Steps to reproduce (in staging, build on 25.07.2018 @ 09:45:01 UTC):

1. Upload a file (I used Montserrat-5.001.zip)
1. New process with default workflow
1. tick the "Feature extraction" checkbox
1. start process

* job report status is done, but in red which usually means a failure happened somewhere, but no failures are present in subreports
* AIP is not created (Outcome intellectual entity shows the AIP being ingested and clicking it returns 404)
* Executed 4 of 7 tasks (57%)
* "Run tasks" shows:

```
1. Uploaded file/folder
Agent: org.roda.core.plugins.plugins.ingest.TransferredResourceToAIPPlugin (1.0)
Outcome: Success

2. AIP metadata validation
Agent: org.roda.core.plugins.plugins.base.DescriptiveMetadataValidationPlugin (1.0)
Outcome: Success

3. Fixity information computation
Agent: org.roda.core.plugins.plugins.characterization.PremisSkeletonPlugin (1.0)
Outcome: Success

4. File format identification (Siegfried)
Agent: org.roda.core.plugins.plugins.characterization.SiegfriedPlugin (1.7.8 w/ DROID_SignatureFile_V93)
Outcome: Success
```

**Comment by hsilva-keep** [comment]
Just for future memory, the exception thrown is
```
2018-07-25 12:17:05,365 [JobsSystem-io-2-dispatcher-34] ERROR o.r.c.p.o.akka.AkkaWorkerActor - Error executing plugin.execute()
java.lang.AbstractMethodError: null
        at org.roda.core.plugins.AbstractAIPComponentsPlugin$1.process(AbstractAIPComponentsPlugin.java:47)
        at org.roda.core.plugins.plugins.PluginHelper.processObjects(PluginHelper.java:145)
        at org.roda.core.plugins.plugins.PluginHelper.processObjects(PluginHelper.java:128)
        at org.roda.core.plugins.AbstractAIPComponentsPlugin.execute(AbstractAIPComponentsPlugin.java:40)
        at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.executePlugin(DefaultIngestPlugin.java:665)
        at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.doFeatureAndFullTextExtraction(DefaultIngestPlugin.java:637)
        at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.processObjects(DefaultIngestPlugin.java:243)
        at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin$1.process(DefaultIngestPlugin.java:150)
        at org.roda.core.plugins.plugins.PluginHelper.processObjects(PluginHelper.java:145)
        at org.roda.core.plugins.plugins.PluginHelper.processObjects(PluginHelper.java:128)
        at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.execute(DefaultIngestPlugin.java:146)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:54)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:39)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:291)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:180)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
which sounds like plugin code is somehow incompatible with RODA's code.

Also, this has some relation with issue #837
