### ISSUE TITLE
Move of a file to root gives NPE while checking permissions

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1343]
- [x] Moving a file that is on a folder to root gives an error
- [x] The move dialog of file that is in root shows the move to root option, giving an error if chosen
- [x] Moving a file that is on a folder to the same folder gives an error
- [x] Consider not showing the move to root option when a file is in root
- [x] Consider not listing the file parent on the select move list
- [x] Even if options are not shown in UI, the backend methods should not fail with NPE

Error moving to root:
```
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.roda.core.data.v2.jobs.Job org.roda.wui.client.browse.BrowserService.moveFiles(java.lang.String,java.lang.String,org.roda.core.data.v2.index.select.SelectedItems,org.roda.core.data.v2.ip.IndexedFile,java.lang.String) throws org.roda.core.data.exceptions.AuthorizationDeniedException,org.roda.core.data.exceptions.GenericException,org.roda.core.data.exceptions.RequestNotValidException,org.roda.core.data.exceptions.AlreadyExistsException,org.roda.core.data.exceptions.NotFoundException' threw an unexpected exception: java.lang.NullPointerException
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:416)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.roda.core.common.UserUtility.checkObjectPermissions(UserUtility.java:162)
	at org.roda.wui.common.ControllerAssistant.checkObjectPermissions(ControllerAssistant.java:65)
	at org.roda.wui.common.ControllerAssistant.checkObjectPermissions(ControllerAssistant.java:59)
	at org.roda.wui.api.controllers.Browser.moveFiles(Browser.java:2489)
	at org.roda.wui.server.browse.BrowserServiceImpl.moveFiles(BrowserServiceImpl.java:703)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	... 33 common frames omitted
```
Report error when moving a file to a folder he already is on:
```
Could not move file: Cannot copy because target path already exists: /roda/data/storage/aip/e85e5a7b-c2e1-4336-9aae-eed5d7106978/representations/a1b20479-2c0b-4faa-a60d-b6186e27bcca/data/test/job.json
```

**Comment by chalkos** [comment]
Fixed.
