### ISSUE TITLE
Error when SIP update fails in default ingest due to NO_OUTCOME_ID

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1364]
There is logic associated with the outcome object if being null or absent that is not being respected now that an AIP become with a value of "NO_OUTCOME_ID". One of the problems that arise is the following error in case of a ingest SIP update failure (e.g. in the case where the AIP to be updated does not exist).

```
2018-10-04 10:24:02,839 [JobsSystem-io-2-dispatcher-48] DEBUG o.r.c.p.p.i.-.DefaultIngestPlugin - Getting AIPs: [NO_OUTCOME_ID]
2018-10-04 10:24:02,839 [JobsSystem-io-2-dispatcher-39] DEBUG o.r.c.p.p.i.-.DefaultIngestPlugin - Getting AIPs: [NO_OUTCOME_ID]
2018-10-04 10:24:02,836 [JobsSystem-akka.actor.default-dispatcher-4] ERROR o.r.c.p.o.akka.DeadLetterActor - Dead letter: DeadLetter(JobsManagerReplyToReleaseLock [lites=[]],Actor[akka://JobsSystem/user/jobsManager#874174081],Actor[akka://JobsSystem/deadLetters])
2018-10-04 10:24:02,840 [JobsSystem-akka.actor.default-dispatcher-4] ERROR o.r.c.p.o.akka.DeadLetterActor - Dead letter: DeadLetter(JobsManagerReplyToReleaseLock [lites=[]],Actor[akka://JobsSystem/user/jobsManager#874174081],Actor[akka://JobsSystem/deadLetters])
2018-10-04 10:24:02,840 [JobsSystem-io-2-dispatcher-48] ERROR o.r.c.p.p.i.-.DefaultIngestPlugin - Error while retrieving AIP
org.roda.core.data.exceptions.NotFoundException: Cannot find file or directory at /roda/data/storage/aip/NO_OUTCOME_ID/aip.json
        at org.roda.core.storage.fs.FSUtils.convertPathToResource(FSUtils.java:611)
        at org.roda.core.storage.fs.FileStorageService.getBinary(FileStorageService.java:420)
        at org.roda.core.model.utils.ResourceParseUtils.getAIPMetadata(ResourceParseUtils.java:362)
        at org.roda.core.model.utils.ResourceParseUtils.getAIPMetadata(ResourceParseUtils.java:349)
        at org.roda.core.model.ModelService.retrieveAIP(ModelService.java:239)
        at org.roda.core.plugins.plugins.ingest.-.DefaultIngestPlugin.getAIPsFromReports(DefaultIngestPlugin.java:385)
        at org.roda.core.plugins.plugins.ingest.-.DefaultIngestPlugin.processObjects(DefaultIngestPlugin.java:182)
        at org.roda.core.plugins.plugins.ingest.-.DefaultIngestPlugin$1.process(DefaultIngestPlugin.java:153)
        at org.roda.core.plugins.plugins.PluginHelper.processObjects(PluginHelper.java:146)
        at org.roda.core.plugins.plugins.PluginHelper.processObjects(PluginHelper.java:128)
        at org.roda.core.plugins.plugins.ingest.-.DefaultIngestPlugin.execute(DefaultIngestPlugin.java:149)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:54)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:39)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:291)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:180)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by luis100** [comment]
Even when there is a change in DefaultIngestPlugin.getAIPsFromReports() to ignore AIP ids from reports that are `NO_OUTCOME_ID`, then the same kind of error happens in DefaultIngestPlugin.createIngestEvent(), as it is not expecting the `NO_OUTCOME_ID`. This points to a solution in the IngestJobPluginInfo. But it is not clear if this would not affect the logic that was the reason to introduce the `NO_OUTCOME_ID` in the first place.
