### ISSUE TITLE
Cannot create an AIP using web user interface

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1468]
How to reproduce:
* docker pull keeps/roda
* docker run -p 8181:8080 keeps/roda
* Login and create new intellectual entity. Then, error happens.

Log:
```
2019-05-09 14:56:25,707 [http-nio-8080-exec-7] ERROR o.r.w.s.browse.BrowserServiceImpl - Unexpected failure
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.roda.wui.client.browse.BrowserService.retrieveSupportedMetadata(java.lang.String,java.lang.String,java.
lang.String) throws org.roda.core.data.exceptions.RODAException' threw an unexpected exception: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
        at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:416)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
        at java.util.ResourceBundle.getString(ResourceBundle.java:407)
        at org.roda.core.common.Messages.getTranslation(Messages.java:55)
        at org.roda.wui.api.controllers.BrowserHelper.retrieveSupportedMetadata(BrowserHelper.java:1956)
        at org.roda.wui.api.controllers.Browser.retrieveSupportedMetadata(Browser.java:1964)
        at org.roda.wui.server.browse.BrowserServiceImpl.retrieveSupportedMetadata(BrowserServiceImpl.java:479)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        ... 38 common frames omitted
```

RODA version:
```
{
  "git.branch" : "a52cb137abad0028d9cd3047967dcd29933a596d",
  "git.build.host" : "travis-job-538af9eb-6512-4ffc-b0b8-7765ddec7727",
  "git.build.number" : "",
  "git.build.number.unique" : "",
  "git.build.time" : "2019-04-30T16:10:56+0000",
  "git.build.user.email" : "travis@example.org",
  "git.build.user.name" : "Travis CI User",
  "git.build.version" : "3.1.1-SNAPSHOT",
  "git.closest.tag.commit.count" : "1",
  "git.closest.tag.name" : "v3.1.0",
  "git.commit.id" : "a52cb137abad0028d9cd3047967dcd29933a596d",
  "git.commit.id.abbrev" : "a52cb13",
  "git.commit.id.describe" : "v3.1.0-1-ga52cb13-dirty",
  "git.commit.id.describe-short" : "v3.1.0-1-dirty",
  "git.commit.message.full" : "Setting version 3.1.1-SNAPSHOT",
  "git.commit.message.short" : "Setting version 3.1.1-SNAPSHOT",
  "git.commit.time" : "2019-04-30T15:58:39+0000",
  "git.commit.user.email" : "lfaria@keep.pt",
  "git.commit.user.name" : "Luis Faria",
  "git.dirty" : "true",
  "git.remote.origin.url" : "https://github.com/keeps/roda.git",
  "git.tags" : "",
  "git.total.commit.count" : "50"
}
```

**Comment by hsilva-keep** [comment]
Minor update: it happens in Google Chrome version 73.0.3683.103 but in in Firefox (in the same host).
