### ISSUE TITLE
Error 500 on /gwtrpc/userlogin

### ISSUE THREAD

**Issue by abcydybcy** [keeps/roda#1511]
Hi,
While trying to set up RODA docker image for demo, we've run into an issue.
RODA won't load because of an error 500 on `/gwtrpc/userlogin`.
Set up w/ docker, `docker run -p 9080:8080 -v /opt/roda:/roda --name roda -d keeps/roda`.
It has worked yesterday for a while, now even recreating a container won't fix it. `/opt/roda` is empty. Running on CentOS Linux release 7.7.1908 (Core), Linux version 3.10.0-1062.4.1.el7.x86_64.

Tomcat log:
```
27-Nov-2019 08:33:57.871 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.ApplicationContext.log Exception while dispatching incoming RPC call
	com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.roda.core.data.v2.user.User org.roda.wui.client.common.UserLoginService.getAuthenticatedUser() throws org.roda.core.data.exceptions.RODAException' threw an unexpected exception: java.lang.NullPointerException
		at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:416)
		at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
		at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
		at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
		at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
		at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.NullPointerException
		at org.roda.core.common.UserUtility.getGuest(UserUtility.java:239)
		at org.roda.core.common.UserUtility.getUser(UserUtility.java:84)
		at org.roda.core.common.UserUtility.getUser(UserUtility.java:96)
		at org.roda.wui.server.common.UserLoginServiceImpl.getAuthenticatedUser(UserLoginServiceImpl.java:46)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
		... 37 more
```

**Comment by lodnert** [comment]
I got this error, not using docker. Any updates?

**Comment by luis100** [comment]
This error refers to a NPE on:
https://github.com/keeps/roda/blob/3916b6146261f9302aba3b2714d84e693c8679c3/roda-core/roda-core/src/main/java/org/roda/core/common/UserUtility.java#L239

This seems to be an initialization error on the local LDAP user base, the "guest" user should always exist. There should be a previous error in the log pointing to the underlying reason. Most probably, the local LDAP user base could not initialize due to some problem (folder permissions? bad configuration?).

**Comment by luis100** [comment]
The log where this initialization error should appear should be the `roda-core.log`, within the RODA HOME. In docker, at /roda/logs folder. If not using RODA, RODA_HOME default to `~/.roda`

**Comment by lodnert** [comment]
Ok, will check the logs. Where is Ldap settings configured?

**Comment by luis100** [comment]
https://github.com/keeps/roda/blob/3916b6146261f9302aba3b2714d84e693c8679c3/roda-core/roda-core/src/main/resources/config/roda-core.properties#L18-L54

**Comment by luis100** [comment]
Closing due to inactivity

**Comment by pabe1250** [comment]
I can reproduce this exact error on RODA 4.

In my case the issue was that the ~/.roda-folder was owned by root. Changed it to current user and all came up nicely.

/Paul
