### ISSUE TITLE
RODA exception on start

### ISSUE THREAD

**Issue by diglesias26** [keeps/roda#2243]
Hi community, 

On July I deployed the roda image from  github on an cloud container and everything seemed to work fine.

Last week I tried to start the container but I only got a partial welcome page when connecting to the repo url, since I didn't see the bar with "Login" and "Language" links.

The tomcat's localhost.log log reported:
root@SandboxHost-638012581651066674:/usr/local/tomcat/logs# more localhost.2022-10-13.log
13-Oct-2022 11:44:22.425 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log 1 Spring WebApplicationInitializers detected on classpath
13-Oct-2022 11:45:42.369 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.loadOnStartup Servlet [RodaWuiServlet] in web application [] threw load() exception
        org.roda.wui.servlets.RodaCoreInstantiationException: RODA Core didn't start because errors have occurred! Please see RODA logs to understand why...
                at org.roda.wui.servlets.RodaWuiServlet.init(RodaWuiServlet.java:31)
                at javax.servlet.GenericServlet.init(GenericServlet.java:158)
                at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1173)
                at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1118)
                at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1011)
                at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4952)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5266)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:727)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
                at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1177)
                at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1925)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:750)
13-Oct-2022 11:47:09.133 SEVERE [http-nio-8080-exec-9] org.apache.catalina.core.ApplicationContext.log Exception while dispatching incoming RPC call
        com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.roda.core.data.v2.user.User org.roda.wui.client.common.UserLoginService.getAuthenticatedUser() throws org.roda.core.data.exceptions.RODAException' threw an unexpected exception: java.lang.NullPointerException
                at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:416)
                at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
                at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
                at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
                at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
                at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:682)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:765)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)				
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:662)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:882)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1693)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:750)
        Caused by: java.lang.NullPointerException
                at org.roda.core.common.UserUtility.getGuest(UserUtility.java:239)
                at org.roda.core.common.UserUtility.getUser(UserUtility.java:84)
                at org.roda.core.common.UserUtility.getUser(UserUtility.java:96)
                at org.roda.wui.server.common.UserLoginServiceImpl.getAuthenticatedUser(UserLoginServiceImpl.java:46)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
                ... 37 more

and roda-core.log
root@SandboxHost-638012581651066674:/roda/log# more roda-core.log 
2022-10-13 11:44:23,200 [localhost-startStop-1] DEBUG org.roda.core.RodaCoreFactory - RODA HOME is /roda
2022-10-13 11:44:24,271 [localhost-startStop-1] INFO  org.roda.core.RodaCoreFactory - Copying files from classpath prefix=config/, destinatio
n=/roda/example-config, removePrefix=true, excludePaths=[config/ldap, config/i18n/client, config/i18n/I18N.gwt.xml]
2022-10-13 11:44:36,855 [localhost-startStop-1] DEBUG org.roda.core.RodaCoreFactory - Finished instantiating essential directories
2022-10-13 11:44:36,997 [localhost-startStop-1] DEBUG org.roda.core.RodaCoreFactory - Loaded roda-core.properties
2022-10-13 11:44:37,097 [localhost-startStop-1] DEBUG org.roda.core.RodaCoreFactory - Loaded roda-roles.properties
2022-10-13 11:44:37,128 [localhost-startStop-1] DEBUG org.roda.core.RodaCoreFactory - Loaded roda-permissions.properties
2022-10-13 11:44:37,174 [localhost-startStop-1] DEBUG org.roda.core.RodaCoreFactory - Going to instantiate Filesystem on '/roda/data/storage'
2022-10-13 11:44:37,239 [localhost-startStop-1] WARN  o.r.c.storage.fs.FileStorageService - Trying to initialize /roda/data/storage-history/data/aip but parent is not writable
2022-10-13 11:44:37,242 [localhost-startStop-1] WARN  o.r.c.storage.fs.FileStorageService - Trying to initialize /roda/data/storage-history/metadata/aip but parent is not writable
2022-10-13 11:44:37,265 [localhost-startStop-1] DEBUG org.roda.core.RodaCoreFactory - Finished instantiating storage...
2022-10-13 11:44:37,783 [localhost-startStop-1] DEBUG org.roda.core.RodaCoreFactory - Finished instantiating model...
2022-10-13 11:44:37,783 [localhost-startStop-1] DEBUG org.roda.core.RodaCoreFactory - Finished instantiating storage & model
2022-10-13 11:44:37,813 [localhost-startStop-1] INFO  org.roda.core.RodaCoreFactory - Using SOLR home: /usr/local/tomcat/temp/rodaWorkingDirectory3930527471734859090/index8849106390336461611/config/index
2022-10-13 11:44:37,828 [localhost-startStop-1] INFO  org.roda.core.RodaCoreFactory - Instantiating SOLR Cloud at localhost:2181
2022-10-13 11:44:38,338 [localhost-startStop-1] INFO  org.roda.core.RodaCoreFactory - Connecting to Solr Cloud with a timeout of 60000 ms...
2022-10-13 11:44:38,471 [localhost-startStop-1-SendThread(localhost:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1275)
2022-10-13 11:44:39,587 [localhost-startStop-1-SendThread(localhost:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1275)
2022-10-13 11:44:40,699 [localhost-startStop-1-SendThread(localhost:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1275)
2022-10-13 11:44:41,811 [localhost-startStop-1-SendThread(localhost:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1275)
2022-10-13 11:44:42,924 [localhost-startStop-1-SendThread(localhost:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1275)
[...]

It seems something related with communications but I'm not aware of any change in the "box".
Any ideas?

Thanks in advance.

**Comment by luis100** [comment]
Hi, main issue seems to be "java.net.ConnectException: Connection refused" when connecting to Zookeeper. So please check the Zookeeper connect configuration and check if there is conectivity between RODA and Zookeeper.

**Comment by luis100** [comment]
Looking a bit more, it seems that you have configured Zookeeper config as " localhost/127.0.0.1:2181", note that if RODA is running in a container, localhost will be the SAME container. If you are running Zookeeper as a separate service in the same docker compose, that you need to put the docker service name, if you are running Zookeeper as a external service that maps port to the host that is running Docker, you need to use the host IP address.

**Comment by tomaszkrym** [comment]
@luis100 I have got same problem just with running demo following the steps in https://github.com/keeps/roda/blob/master/documentation/Installation_Testing_Environments.md#installation

**Comment by luis100** [comment]
@tomaszkrym that documentation is outdated, please try this instead:
https://github.com/keeps/roda/tree/master/deploys/standalone

Note: we no longer support Windows has a host for RODA services.

**Comment by tomaszkrym** [comment]
@luis100 thank you, I am trying to run RODA on Ubuntu 22.04. I tried the running the docker compose from link that you provided, but demo installation doesn't work either (with different log). I feel that it might be root cause for #2231 

The server side log:

`022-10-20 10:17:16,219 [main] DEBUG org.roda.core.RodaCoreFactory - Going to instantiate Filesystem on '/roda/data/storage'
2022-10-20 10:17:16,223 [main] WARN  o.r.c.storage.fs.FileStorageService - Trying to initialize /roda/data/storage-history/data/aip but parent is not writable
2022-10-20 10:17:16,223 [main] WARN  o.r.c.storage.fs.FileStorageService - Trying to initialize /roda/data/storage-history/metadata/aip but parent is not writable
2022-10-20 10:17:16,223 [main] DEBUG org.roda.core.RodaCoreFactory - Finished instantiating storage...
2022-10-20 10:17:16,235 [main] DEBUG org.roda.core.RodaCoreFactory - Finished instantiating model...
2022-10-20 10:17:16,236 [main] DEBUG org.roda.core.RodaCoreFactory - Finished instantiating storage & model
2022-10-20 10:17:16,237 [main] DEBUG org.roda.core.RodaCoreFactory - Finished instantiating distributed mode
2022-10-20 10:17:16,237 [main] INFO  org.roda.core.RodaCoreFactory - Using SOLR home: /usr/local/tomcat/temp/rodaWorkingDirectory11641862085073912623/index12767239479057490247/config/index
2022-10-20 10:17:16,241 [main] INFO  org.roda.core.RodaCoreFactory - Instantiating SOLR Cloud at zoo:2181
2022-10-20 10:17:16,416 [main] INFO  org.roda.core.RodaCoreFactory - Connecting to Solr Cloud with a timeout of 60000 ms...
2022-10-20 10:17:16,555 [main] INFO  org.roda.core.RodaCoreFactory - Connected to Solr Cloud
2022-10-20 10:17:16,556 [main] INFO  org.roda.core.RodaCoreFactory - Live nodes: [172.18.0.2:8983_solr, 172.19.0.2:8983_solr]
2022-10-20 10:17:16,556 [main] INFO  org.roda.core.RodaCoreFactory - All available Solr Cloud collections are healthy, collections: []
2022-10-20 10:17:31,649 [main] ERROR org.roda.core.RodaCoreFactory - Solr bootstrap failed
org.apache.solr.client.solrj.SolrServerException: IOException occured when talking to server at: null
        at org.apache.solr.client.solrj.impl.Http2SolrClient.request(Http2SolrClient.java:469)
        at org.apache.solr.client.solrj.impl.LBSolrClient.doRequest(LBSolrClient.java:401)
        at org.apache.solr.client.solrj.impl.LBSolrClient.request(LBSolrClient.java:369)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1248)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:969)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:896)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:217)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:232)
        at org.roda.core.RodaCoreFactory.bootstrap(RodaCoreFactory.java:1389)
        at org.roda.core.RodaCoreFactory.instantiateSolr(RodaCoreFactory.java:1270)
        at org.roda.core.RodaCoreFactory.instantiateSolrAndIndexService(RodaCoreFactory.java:1200)
        at org.roda.core.RodaCoreFactory.instantiate(RodaCoreFactory.java:522)
        at org.roda.core.RodaCoreFactory.instantiate(RodaCoreFactory.java:379)
        at org.roda.wui.servlets.RodaWuiServlet.init(RodaWuiServlet.java:27)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1164)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1117)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1010)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4958)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5265)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1185)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1933)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
        at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1095)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:477)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:265)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
Caused by: java.net.SocketTimeoutException: null
        at java.base/sun.nio.ch.SocketAdaptor.connect(Unknown Source)
        at org.eclipse.jetty.http2.client.HTTP2Client.connect(HTTP2Client.java:432)
        at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2.connect(HttpClientTransportOverHTTP2.java:151)
        at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2.connect(HttpClientTransportOverHTTP2.java:146)
        at org.eclipse.jetty.client.HttpClient$1.connect(HttpClient.java:638)
        at org.eclipse.jetty.client.HttpClient$1.succeeded(HttpClient.java:615)
        at org.eclipse.jetty.client.HttpClient$1.succeeded(HttpClient.java:607)
        at org.eclipse.jetty.util.SocketAddressResolver$Async.lambda$resolve$1(SocketAddressResolver.java:186)
        at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:259)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by luis100** [comment]
Ok, I think I got what the problem was. The demo deployment was pointing to "keeps/roda:development" image instead of "keeps/roda:latest". The development image now uses Solr 9 which was then making all the problem.

I've updated the code, you can "git pull" or change the RODA image from development tag to latest.

To start this up now, you might need to reset your environment.

```sh
git pull
docker compose down
docker compose pull
docker container prune -f # or delete the old containers by name
docker volume prune -f # or delete the old volumes by name
```
Try this up and let me know if it works.

**Comment by luis100** [comment]
Another note, if you want to sneak-preview RODA 5, you can checkout the development branch and run the same standalone deployment, this turn it will use RODA "development" image but also update Solr to version 9. You'll may need to reset your system to ensure there is no upgrading problems.

@diglesias26 if you want to use RODA on more that a once-off demo trial, you should fix the specific RODA version on the image, using "v4.4.0" instead of "latest".The "latest" and "development" tags will roam freely with the latest stable or development branches. When we release a new stable version we might change the requirements, as we did in terms of Solr because Solr 7.X has reached end-of-life. We had warned about this on https://github.com/keeps/roda/releases/tag/v4.4.0
So to continue to use an (outdated and unsupported) Solr 7.X you need to use a version lower than 4.4.0.

**Comment by tomaszkrym** [comment]
@luis100 it works now, thank you!

**Comment by diglesias26** [comment]
Thanks Luis!
