### ISSUE TITLE
Error occurs when searching for a query with " - "

### ISSUE THREAD

**Issue by luis100** [keeps/roda#226]
When doing a search using the `BasicSearchFieldParameter`, if the query contains a " - " an error occurs.

Example query: `acrobat pdf 1.3 - portable document format`

```
2016-02-29 12:00:07,689 ERROR o.a.solr.handler.RequestHandlerBase - org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse '(search: (acrobat) AND search: (pdf) AND search: (1.3) AND search: (-) AND search: (portable) AND search: (document) AND search: (format)) AND (fileFormat: *) AND (formatMimetype: *)': Encountered " ")" ") "" at line 1, column 69.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    "filter(" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
    
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:216)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:246)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2082)
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:178)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:942)
	at org.roda.core.index.utils.SolrUtils.find(SolrUtils.java:797)
	at org.roda.core.index.IndexService.find(IndexService.java:100)
	at org.roda.wui.api.controllers.BrowserHelper.find(BrowserHelper.java:245)
	at org.roda.wui.api.controllers.Browser.find(Browser.java:146)
	at org.roda.wui.server.browse.BrowserServiceImpl.find(BrowserServiceImpl.java:137)
	at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:68)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.search.SyntaxError: Cannot parse '(search: (acrobat) AND search: (pdf) AND search: (1.3) AND search: (-) AND search: (portable) AND search: (document) AND search: (format)) AND (fileFormat: *) AND (formatMimetype: *)': Encountered " ")" ") "" at line 1, column 69.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    "filter(" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
    
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:157)
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)
	at org.apache.solr.search.QParser.getQuery(QParser.java:141)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:159)
	... 46 more
Caused by: org.apache.solr.parser.ParseException: Encountered " ")" ") "" at line 1, column 69.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    "filter(" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
    
	at org.apache.solr.parser.QueryParser.generateParseException(QueryParser.java:665)
	at org.apache.solr.parser.QueryParser.jj_consume_token(QueryParser.java:547)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:232)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:107)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:190)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:140)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:190)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:107)
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:153)
	... 49 more

```

**Comment by hsilva-keep** [comment]
Done since 31cdcf47350ffe01826596eca93b00a0fef75b16
