### ISSUE TITLE
Concurrency problem on job update

### ISSUE THREAD

**Issue by luis100** [keeps/roda#274]
```
2016-03-22 12:22:32,754 [WorkersSystem-akka.actor.default-dispatcher-8] ERROR org.roda.core.model.ModelService - Error creating/updating job in storage
org.roda.core.data.exceptions.GenericException: Could not update binary content
        at org.roda.core.storage.fs.FileStorageService.updateBinaryContent(FileStorageService.java:356) ~[roda-core.jar:na]
        at org.roda.core.model.ModelService.createOrUpdateJob(ModelService.java:1387) ~[roda-core.jar:na]
        at org.roda.core.plugins.plugins.PluginHelper.updateJobStatus(PluginHelper.java:343) [roda-core.jar:na]
        at org.roda.core.plugins.plugins.PluginHelper.updateJobStatus(PluginHelper.java:324) [roda-core.jar:na]
        at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.execute(DefaultIngestPlugin.java:243) [roda-core.jar:na]
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:43) [roda-core.jar:na]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) [akka-actor_2.11-2.4.2.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480) [akka-actor_2.11-2.4.2.jar:na]
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) [akka-actor_2.11-2.4.2.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.2.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.nio.file.FileAlreadyExistsException: /home/lfaria/.roda/data/storage/Job/3210ea18-03f6-43a3-a5b4-54c6fda4f93d
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88) ~[na:1.8.0_74]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_74]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_74]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_74]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[na:1.8.0_74]
        at java.nio.file.Files.newOutputStream(Files.java:216) ~[na:1.8.0_74]
        at java.nio.file.Files.copy(Files.java:3016) ~[na:1.8.0_74]
        at org.roda.core.storage.StringContentPayload.writeToPath(StringContentPayload.java:37) ~[roda-core.jar:na]
        at org.roda.core.storage.fs.FileStorageService.updateBinaryContent(FileStorageService.java:354) ~[roda-core.jar:na]
        ... 17 common frames omitted
```

**Comment by hsilva-keep** [comment]
Solved (since 1f3499598ba4780381492cb12845512827ec96a1).
