### ISSUE TITLE
Transferred Resource cannot have comma in the name otherwise index.findById will fail

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#275]
2016-03-22 15:09:41,577 [WorkersSystem-akka.actor.default-dispatcher-5] ERROR o.r.c.p.o.akka.AkkaJobWorkerActor - Error retrieving TransferredResource
org.roda.core.data.exceptions.NotFoundException: Could not find document Pereira et al, Revista Portuguesa de Ciencias Veterinarias 2005.pdf
	at org.roda.core.index.utils.SolrUtils.retrieve(SolrUtils.java:850) ~[roda-core.jar:na]
	at org.roda.core.index.IndexService.retrieve(IndexService.java:118) ~[roda-core.jar:na]
	at org.roda.core.plugins.orchestrate.akka.AkkaJobWorkerActor.getTransferredResourcesFromObjectIds(AkkaJobWorkerActor.java:67) [roda-core.jar:na]

**Comment by hsilva-keep** [comment]
Solved (since df135603c35f8fb044980acc727453de1c9c1fef).
