### ISSUE TITLE
Error adding other Tika properties to indexed file

### ISSUE THREAD

**Issue by luis100** [keeps/roda#284]
```
2016-04-02 14:27:13,971 [WorkersSystem-akka.actor.default-dispatcher-214] ERROR o.roda.core.index.IndexModelObserver - Error adding other properties to indexed file: The entity name must immediately follow the '&' in the entity reference.
org.xml.sax.SAXParseException: The entity name must immediately follow the '&' in the entity reference.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) ~[na:1.8.0_77]
	at org.roda.core.common.MetadataFileUtils.parseBinary(MetadataFileUtils.java:84) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.index.utils.SolrUtils.addOtherPropertiesToIndexedFile(SolrUtils.java:2088) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.index.IndexModelObserver.otherMetadataCreated(IndexModelObserver.java:550) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.model.ModelObservable.notifyOtherMetadataCreated(ModelObservable.java:192) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.model.ModelService.createOtherMetadata(ModelService.java:1053) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.characterization.TikaFullTextPluginUtils.runTikaFullTextOnRepresentation(TikaFullTextPluginUtils.java:96) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.characterization.TikaFullTextPlugin.execute(TikaFullTextPlugin.java:119) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.executePlugin(DefaultIngestPlugin.java:536) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.doFeatureAndFullTextExtraction(DefaultIngestPlugin.java:496) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.execute(DefaultIngestPlugin.java:271) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:43) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
```

**Comment by luis100** [comment]
The `TikaFullTextPluginUtils#runTikaFullTextOnRepresentation(...)` is set to notify on each file created. Instead, add indexing of metadata to `IndexModelObserver#indexFile(AIP,File,boolean)`.

**Comment by luis100** [comment]
The Tika metadata file is created with no care of XML entities escaping on the "name" attribute. This error is most probably due to this.

**Comment by luis100** [comment]
Similar error:

```
2016-04-02 14:37:58,458 [WorkersSystem-akka.actor.default-dispatcher-171] ERROR o.roda.core.index.IndexModelObserver - Error adding other properties to indexed file: Character reference "&#4" is an invalid XML character.
org.xml.sax.SAXParseException: Character reference "&#4" is an invalid XML character.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) ~[na:1.8.0_77]
	at org.roda.core.common.MetadataFileUtils.parseBinary(MetadataFileUtils.java:84) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.index.utils.SolrUtils.addOtherPropertiesToIndexedFile(SolrUtils.java:2088) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.index.IndexModelObserver.otherMetadataCreated(IndexModelObserver.java:550) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.model.ModelObservable.notifyOtherMetadataCreated(ModelObservable.java:192) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.model.ModelService.createOtherMetadata(ModelService.java:1053) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.characterization.TikaFullTextPluginUtils.runTikaFullTextOnRepresentation(TikaFullTextPluginUtils.java:96) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.characterization.TikaFullTextPlugin.execute(TikaFullTextPlugin.java:119) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.executePlugin(DefaultIngestPlugin.java:536) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.doFeatureAndFullTextExtraction(DefaultIngestPlugin.java:496) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.execute(DefaultIngestPlugin.java:271) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:43) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
```

**Comment by sleroux-keep** [comment]
I've updated the Key-Value metadata handling (org.roda.core.common.MetadataFileUtils)... It should fix the issue, but i need files with special properties to test it...

**Comment by luis100** [comment]
The new method used is not strong enough to deal with content that comes from Apacke Tika. Some characters can be encoded, other special characters will need to be removed or replaced by their unicode encoding, as they make the resulting XML invalid. There is already an example available (talk with @hsilva-keep). Please strengthen the method to cope with this content.

**Comment by jmaferreira** [comment]
Talk to @chalkos. He has the ultimate escape function.

**Comment by chalkos** [comment]
I'm using a custom implementation based on this: https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringEscapeUtils.html

Since it is just XML, `#escapeXml110` or `#escapeXml111` may be enough for this case.

**Comment by sleroux-keep** [comment]
I've updated the MetadataFileUtils class, and added a Unit Test ( org.roda.core.common.MetadataFileUtilsEscapeTest ) that creates a XML with UTF-16 characters.
