### ISSUE TITLE
Tika errors should be on the report but not logged as errors

### ISSUE THREAD

**Issue by luis100** [keeps/roda#285]
When running Tika on ingest the following error is found in log. Instead of logging this error in the logger, this error should be pretty printed into the plugin report, which should be set as plugin failed.

```
2016-04-02 14:32:35,345 [WorkersSystem-akka.actor.default-dispatcher-187] ERROR o.r.c.p.p.i.c.TikaFullTextPluginUtils - Error running Apache Tika
org.roda.core.data.exceptions.GenericException: Could not create binary
	at org.roda.core.storage.fs.FileStorageService.createBinary(FileStorageService.java:299) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.model.ModelService.createOtherMetadata(ModelService.java:1043) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.characterization.TikaFullTextPluginUtils.runTikaFullTextOnRepresentation(TikaFullTextPluginUtils.java:82) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.characterization.TikaFullTextPlugin.execute(TikaFullTextPlugin.java:119) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.executePlugin(DefaultIngestPlugin.java:536) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.doFeatureAndFullTextExtraction(DefaultIngestPlugin.java:496) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.execute(DefaultIngestPlugin.java:271) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:43) [roda-core-2.0.0-SNAPSHOT.jar:na]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.io.IOException: 
	at org.apache.tika.parser.ParsingReader.read(ParsingReader.java:274) ~[tika-core-1.11.jar:1.11]
	at org.apache.commons.io.input.ReaderInputStream.fillBuffer(ReaderInputStream.java:198) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.input.ReaderInputStream.read(ReaderInputStream.java:242) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.input.ReaderInputStream.read(ReaderInputStream.java:261) ~[commons-io-2.4.jar:2.4]
	at java.nio.file.Files.copy(Files.java:2908) ~[na:1.8.0_77]
	at java.nio.file.Files.copy(Files.java:3027) ~[na:1.8.0_77]
	at org.roda.core.storage.InputStreamContentPayload.writeToPath(InputStreamContentPayload.java:40) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	at org.roda.core.storage.fs.FileStorageService.createBinary(FileStorageService.java:289) ~[roda-core-2.0.0-SNAPSHOT.jar:na]
	... 19 common frames omitted
Caused by: org.apache.tika.exception.TikaException: XML parse error
	at org.apache.tika.parser.xml.XMLParser.parse(XMLParser.java:78) ~[tika-parsers-1.11.jar:1.11]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[tika-core-1.11.jar:1.11]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[tika-core-1.11.jar:1.11]
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) ~[tika-core-1.11.jar:1.11]
	at org.apache.tika.parser.ParsingReader$ParsingTask.run(ParsingReader.java:235) ~[tika-core-1.11.jar:1.11]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_77]
Caused by: org.xml.sax.SAXParseException: The markup in the document following the root element must be well-formed.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLDocumentScannerImpl$TrailingMiscDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195) ~[na:1.8.0_77]
	at org.apache.tika.parser.xml.XMLParser.parse(XMLParser.java:72) ~[tika-parsers-1.11.jar:1.11]
	... 5 common frames omitted

```

**Comment by sleroux-keep** [comment]
I've updated the plugin to add the Tika stackstrace to the Plugin Report (see TikaFullTextPluginUtils )

It need to be tested

**Comment by luis100** [comment]
Please provide an example output. Also, always test before passing the issue to me. 
The output should not be a stack trace but pretty-printed. This means the end cause message should be found and added to the report, as it is the most relevant information. In the case above the report message should be: `The markup in the document following the root element must be well-formed.`.

**Comment by sleroux-keep** [comment]
Report:
![tika](https://cloud.githubusercontent.com/assets/2727798/16052694/3fd0e376-325d-11e6-9559-9e69d5863e76.png)

Premis Event:
![tikaoutcome](https://cloud.githubusercontent.com/assets/2727798/16052704/499328ce-325d-11e6-950f-4ce450f0bee2.png)

**Comment by luis100** [comment]
Cannot test with real data for now (without significant effort), so closing issue. Will re-open if any case is found.
