### ISSUE TITLE
Issue building with tests

### ISSUE THREAD

**Issue by jalshorji** [keeps/roda#2884]
Getting an error while building with tests. 

`13:31:38.802 ERROR o.r.c.p.b.c.SiegfriedPlugin - Error running Siegfried b476d648-f32e-46ae-94ec-db15acd3d982: Error while executing Siegfried: Unable to connect to server, response code: 404
org.roda.core.plugins.PluginException: Error while executing Siegfried: Unable to connect to server, response code: 404
	at org.roda.core.plugins.base.characterization.SiegfriedPluginUtils.runSiegfriedOnPath(SiegfriedPluginUtils.java:89)
	at org.roda.core.plugins.base.characterization.SiegfriedPluginUtils.runSiegfriedOnRepresentationOrFile(SiegfriedPluginUtils.java:203)
	at org.roda.core.plugins.base.characterization.SiegfriedPluginUtils.runSiegfriedOnRepresentation(SiegfriedPluginUtils.java:172)
	at org.roda.core.plugins.base.characterization.SiegfriedPlugin.executeOnAIP(SiegfriedPlugin.java:150)
	at org.roda.core.plugins.AbstractAIPComponentsPlugin$1.process(AbstractAIPComponentsPlugin.java:46)
	at org.roda.core.plugins.PluginHelper.processObjects(PluginHelper.java:154)
	at org.roda.core.plugins.PluginHelper.processObjects(PluginHelper.java:136)
	at org.roda.core.plugins.AbstractAIPComponentsPlugin.execute(AbstractAIPComponentsPlugin.java:39)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:64)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:49)
	at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)`

This is what I see in curl 
{"siegfried":"1.10.0","scandate":"2023-06-19T11:55:48Z","signature":"default.sig","created":"2023-03-23T15:09:43Z","identifiers":[{"name":"pronom","details":"DROID_SignatureFile_V111.xml; container-signature-20230307.xml"}],"files":[{"filename":"/dev/null","filesize": 0,"modified":"2023-06-19T08:27:17Z","errors": "file is of type device; only regular files can be scanned","matches": []}]}

**Comment by jalshorji** [comment]
The problem was related to building the project in macos, and issues with write permissions in mac tmp directory.
