### ISSUE TITLE
VeraPDF test fails when running with other tests

### ISSUE THREAD

**Issue by luis100** [keeps/roda#301]
When running the InternalConvertPluginTest suite, the following error occurs:

```
11:03:49.342 ERROR o.r.c.p.p.i.validation.VeraPDFPlugin - Error processing AIP 35c7446f-3ded-4999-9cc8-159171c3f171: Error: End-of-File, expected line
java.io.IOException: Error: End-of-File, expected line
	at org.apache.pdfbox.shaded.pdfparser.BaseParser.readLine(BaseParser.java:1161)
	at org.apache.pdfbox.shaded.pdfparser.COSParser.parseHeader(COSParser.java:1978)
	at org.apache.pdfbox.shaded.pdfparser.COSParser.parsePDFHeader(COSParser.java:1955)
	at org.apache.pdfbox.shaded.pdfparser.PDFParser.parse(PDFParser.java:264)
	at org.apache.pdfbox.shaded.pdmodel.PDDocument.load(PDDocument.java:1064)
	at org.apache.pdfbox.shaded.pdmodel.PDDocument.load(PDDocument.java:938)
	at org.verapdf.model.ModelParser.<init>(ModelParser.java:31)
	at org.roda.core.plugins.plugins.ingest.validation.VeraPDFPluginUtils.runVeraPDF(VeraPDFPluginUtils.java:44)
	at org.roda.core.plugins.plugins.ingest.validation.VeraPDFPlugin.execute(VeraPDFPlugin.java:154)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:40)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
11:03:49.345 INFO  o.r.c.p.o.AkkaEmbeddedPluginOrchestrator - Ended PDF/A format validator
```

The test is successful if running alone.

**Comment by nunovieira220** [comment]
Since changing test to TestNG, it seems the problem did not occur again.
