### ISSUE TITLE
Error loading EAD 2002 schema (when offline?)

### ISSUE THREAD

**Issue by luis100** [keeps/roda#362]
```
2016-06-19 22:14:59,252 [http-apr-8080-exec-1] ERROR org.roda.core.RodaCoreFactory - Error while loading XML Schema
org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'xlink:extendedLink' to a(n) 'attribute group' component.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.reportSchemaError(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.reportSchemaError(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.getGlobalDecl(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDAttributeGroupTraverser.traverseLocal(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDAbstractTraverser.traverseAttrsAndAttrGrps(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDComplexTypeTraverser.processComplexContent(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDComplexTypeTraverser.traverseGlobal(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.traverseSchemas(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
	at org.apache.xerces.jaxp.validation.XMLSchemaFactory.newSchema(Unknown Source)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
	at org.roda.core.RodaCoreFactory.getRodaSchema(RodaCoreFactory.java:1005)
	at org.roda.core.common.validation.ValidationUtils.validateDescriptiveBinary(ValidationUtils.java:268)
	at org.roda.wui.api.controllers.BrowserHelper.createDescriptiveMetadataFile(BrowserHelper.java:951)
	at org.roda.wui.api.controllers.Browser.createDescriptiveMetadataFile(Browser.java:661)
	at org.roda.wui.server.browse.BrowserServiceImpl.createDescriptiveMetadataFile(BrowserServiceImpl.java:302)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

**Comment by adrapereira** [comment]
Fixed edc10575beb66bdd206890bf9fa7ae0068efbe76
