### ISSUE TITLE
Metadata editor NullPointerException when no template

### ISSUE THREAD

**Issue by luis100** [keeps/roda#368]
```
Caused by: java.lang.NullPointerException
	at org.roda.wui.api.controllers.BrowserHelper.getDescriptiveMetadataEditBundle(BrowserHelper.java:311)
	at org.roda.wui.api.controllers.BrowserHelper.getDescriptiveMetadataEditBundle(BrowserHelper.java:273)
	at org.roda.wui.api.controllers.Browser.getDescriptiveMetadataEditBundle(Browser.java:151)
	at org.roda.wui.server.browse.BrowserServiceImpl.getDescriptiveMetadataEditBundle(BrowserServiceImpl.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	... 31 more
```

**Comment by adrapereira** [comment]
Fixed in 35c20b8947c7d2112ae09e2abf063bda50cac06e
