### ISSUE TITLE
Unexpected error registering log entry

### ISSUE THREAD

**Issue by luis100** [keeps/roda#370]
```
2016-07-02 00:14:38,150 [ajp-nio-8009-exec-9] ERROR org.roda.wui.common.RodaCoreService - Error registering action 'Browser'
org.roda.core.data.exceptions.GenericException: Error creating file to write log into
        at org.roda.core.model.ModelService.addLogEntry(ModelService.java:1141)
        at org.roda.core.model.ModelService.addLogEntry(ModelService.java:1157)
        at org.roda.wui.common.RodaCoreService.registerAction(RodaCoreService.java:35)
        at org.roda.wui.common.RodaCoreService.registerAction(RodaCoreService.java:30)
        at org.roda.wui.api.controllers.Browser.find(Browser.java:197)
        at org.roda.wui.server.browse.BrowserServiceImpl.find(BrowserServiceImpl.java:178)
        at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:868)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileAlreadyExistsException: /apps/KEEPS/roda/data/log/2016-07-02.log
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.createFile(Files.java:632)
        at org.roda.core.model.ModelService.addLogEntry(ModelService.java:1139)
        ... 36 common frames omitted
```

**Comment by luis100** [comment]
This is possibly due the change of file as the day was over, first log in the file is:

```json
{
    "id": "5a2088b8-ddc0-4738-9f84-1bf069ffd2e5",
    "address": "",
    "datetime": 1467411278089,
    "username": "admin",
    "actionComponent": "Browser",
    "actionMethod": "find",
    "relatedObjectID": null,
    "duration": 6,
    "parameters": [{
        "name": "class",
        "value": "Job"
    }, {
        "name": "filter",
        "value": "Filter [parameters=[NotSimpleFilterParameter(name=pluginType, value=INGEST)]]"
    }, {
        "name": "sorter",
        "value": "Sorter ([SortParameter(name=startDate, descending=true)])"
    }, {
        "name": "sublist",
        "value": "Sublist(firstElementIndex=0, maximumElementCount=20)"
    }]
}
```

**Comment by luis100** [comment]
Datetime above is Fri, 01 Jul 2016 22:14:38.089 GMT, server timezone is GMT+2, so date is July 2, 00:14:38.089. This is 61 milliseconds before the error above, which created the file. Concurrency problems when creating a file on day change might be the problem.

**Comment by luis100** [comment]
difficult to test, if it happens again will re-open it.
