### ISSUE TITLE
Error re-indexing risks

### ISSUE THREAD

**Issue by luis100** [keeps/roda#489]
```
2016-09-05 15:12:54,141 [WorkersSystem-akka.actor.default-dispatcher-16] ERROR o.r.c.p.p.b.ReindexAllRodaEntitiesPlugin - Error reindexing (all): Risk
org.roda.core.data.exceptions.GenericException: Error while parsing JSON
	at org.roda.core.data.utils.JsonUtils.getObjectFromJson(JsonUtils.java:129)
	at org.roda.core.index.IndexService.reindex(IndexService.java:284)
	at org.roda.core.plugins.plugins.base.ReindexAllRodaEntitiesPlugin.execute(ReindexAllRodaEntitiesPlugin.java:79)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:49)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:35)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "objectsSize" (class org.roda.core.data.v2.risks.Risk), not marked as ignorable (26 known properties: "notes", "posMitigationProbability", "preMitigationSeverityLevel", "createdOn", "preMitigationImpact", "name", "posMitigationNotes", "posMitigationSeverity", "mitigationRelatedEventIdentifierType", "identifiedBy", "preMitigationProbability", "posMitigationSeverityLevel", "posMitigationImpact", "identifiedOn", "id", "description", "category", "preMitigationSeverity", "mitigationOwnerType", "mitigationStrategy", "mitigationOwner", "mitigationRelatedEventIdentifierValue", "preMitigationNotes", "createdBy", "updatedOn", "updatedBy"])
 at [Source: {"id":"648c6802-813a-4418-a9cc-30a0c0cfcb86","name":"Test risk","description":"","identifiedOn":1467932400000,"identifiedBy":"Miguel Ferreira","category":"Danger","notes":"","preMitigationProbability":0,"preMitigationImpact":0,"preMitigationSeverity":0,"preMitigationSeverityLevel":"LOW","preMitigationNotes":"","posMitigationProbability":0,"posMitigationImpact":0,"posMitigationSeverity":0,"posMitigationSeverityLevel":"LOW","posMitigationNotes":"","mitigationStrategy":"","mitigationOwnerType":"","mitigationOwner":"","mitigationRelatedEventIdentifierType":"","mitigationRelatedEventIdentifierValue":"","objectsSize":0}; line: 1, column: 621] (through reference chain: org.roda.core.data.v2.risks.Risk["objectsSize"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:851)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1085)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1388)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1366)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:266)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797)
	at org.roda.core.data.utils.JsonUtils.getObjectFromJson(JsonUtils.java:127)
	... 16 common frames omitted
```

**Comment by nunovieira220** [comment]
Issue solved.
