### ISSUE TITLE
Error while reindexing all the Jobs

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#522]
2016-09-12 19:00:26,093 [ ] ERROR o.r.c.p.o.akka.AkkaJobStateInfoActor - Unable to get Job from index to log its state change
org.roda.core.data.exceptions.NotFoundException: Could not find document c8b2864e-29bf-4f03-9874-4d60902e3e94
        at org.roda.core.index.utils.SolrUtils.retrieve(SolrUtils.java:177)
        at org.roda.core.index.IndexService.retrieve(IndexService.java:144)
        at org.roda.core.plugins.plugins.PluginHelper.getJob(PluginHelper.java:245)
        at org.roda.core.plugins.orchestrate.akka.AkkaJobStateInfoActor.handleJobStateUpdated(AkkaJobStateInfoActor.java:93)
        at org.roda.core.plugins.orchestrate.akka.AkkaJobStateInfoActor.onReceive(AkkaJobStateInfoActor.java:61)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by hsilva-keep** [comment]
Actually this just happens because we want to log the job state change and for that we try to grab job information from the index. But, as we are reindexing all the jobs, that information doesn't exist and this ugly (with the stacktrace) message is thrown. 
Changed code to just warn, instead of error, that it wasn't possible to get job information (71c7bac2246c1faa79501bd48acac3685eaddbe8).
