### ISSUE TITLE
No enum constant org.roda.core.data.v2.ip.AIPState.false

### ISSUE THREAD

**Issue by sleroux-keep** [keeps/roda#634]
`
2016-10-20 09:04:53,430 [WorkersSystem-akka.actor.default-dispatcher-23] DEBUG o.roda.core.index.IndexModelObserver - Finding descendents of moved aip d2c615cc-c609-4837-9275-bb29040f36d7
2016-10-20 09:04:53,432 [WorkersSystem-akka.actor.default-dispatcher-23] ERROR o.r.c.p.o.akka.AkkaWorkerActor - Error executing plugin.execute()
java.lang.IllegalArgumentException: No enum constant org.roda.core.data.v2.ip.AIPState.false
    at java.lang.Enum.valueOf(Enum.java:238)
    at org.roda.core.data.v2.ip.AIPState.valueOf(AIPState.java:1)
    at org.roda.core.index.utils.SolrUtils.solrDocumentToIndexedAIP(SolrUtils.java:1093)
    at org.roda.core.index.utils.SolrUtils.solrDocumentTo(SolrUtils.java:266)
    at org.roda.core.index.utils.SolrUtils.queryResponseToIndexResult(SolrUtils.java:562)
    at org.roda.core.index.utils.SolrUtils.find(SolrUtils.java:220)
    at org.roda.core.index.utils.SolrUtils.find(SolrUtils.java:204)
    at org.roda.core.index.utils.SolrUtils.execute(SolrUtils.java:2325)
    at org.roda.core.index.IndexModelObserver.aipMoved(IndexModelObserver.java:459)
    at org.roda.core.model.ModelObservable.notifyAipMoved(ModelObservable.java:59)
    at org.roda.core.model.ModelService.moveAIP(ModelService.java:448)
    at org.roda.core.plugins.plugins.PluginHelper.lambda$1(PluginHelper.java:828)
    at org.roda.core.index.utils.SolrUtils.execute(SolrUtils.java:2327)
    at org.roda.core.index.IndexService.execute(IndexService.java:476)
    at org.roda.core.plugins.plugins.PluginHelper.moveChildrenAIPsAndDelete(PluginHelper.java:826)
    at org.roda.core.plugins.plugins.PluginHelper.lambda$0(PluginHelper.java:799)
    at org.roda.core.index.utils.SolrUtils.execute(SolrUtils.java:2327)
    at org.roda.core.index.IndexService.execute(IndexService.java:476)
    at org.roda.core.plugins.plugins.PluginHelper.fixParents(PluginHelper.java:784)
    at org.roda.core.plugins.plugins.base.FixAncestorsPlugin.execute(FixAncestorsPlugin.java:90)
    at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:49)
    at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:35)
    at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
    at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
    at akka.actor.ActorCell.invoke(ActorCell.scala:495)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2016-10-20 09:04:53,433 [WorkersSystem-akka.actor.default-dispatcher-23] INFO  o.r.c.p.o.akka.AkkaJobStateInfoActor - Doing job cleanup
`

**Comment by sleroux-keep** [comment]
Can't reproduce

**Comment by hsilva-keep** [comment]
We have already found where the problem lays & how to reproduce it. So, let's fix it.
