### ISSUE TITLE
Error in roda-in when sending an error report to administrators

### ISSUE THREAD

**Issue by luis100** [keeps/roda#67]
When roda-in configuration has an invalid URL for roda-core (roda.services.url), the following error occurs when sending the error report to administrators:

```
./roda-in.sh 
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at pt.gov.dgarq.roda.sipcreator.RodaSMTPAppender.checkEntryConditions(RodaSMTPAppender.java:37)
	at org.apache.log4j.net.SMTPAppender.append(Unknown Source)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:230)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:65)
	at org.apache.log4j.Category.callAppenders(Category.java:203)
	at org.apache.log4j.Category.forcedLog(Category.java:388)
	at org.apache.log4j.Category.error(Category.java:319)
	at pt.gov.dgarq.roda.sipcreator.SIPCreatorConfig.<init>(SIPCreatorConfig.java:85)
	at pt.gov.dgarq.roda.sipcreator.SIPCreatorConfig.getInstance(SIPCreatorConfig.java:33)
	at pt.gov.dgarq.roda.sipcreator.MainFrame.initComponents(MainFrame.java:148)
	at pt.gov.dgarq.roda.sipcreator.MainFrame.access$000(MainFrame.java:28)
	at pt.gov.dgarq.roda.sipcreator.MainFrame$2.run(MainFrame.java:96)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.NullPointerException
	at pt.gov.dgarq.roda.sipcreator.Messages.getString(Messages.java:35)
	at pt.gov.dgarq.roda.sipcreator.RodaSMTPAppender.checkEntryConditions(RodaSMTPAppender.java:37)
	at org.apache.log4j.net.SMTPAppender.append(Unknown Source)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:230)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:65)
	at org.apache.log4j.Category.callAppenders(Category.java:203)
	at org.apache.log4j.Category.forcedLog(Category.java:388)
	at org.apache.log4j.Category.error(Category.java:319)
	at pt.gov.dgarq.roda.sipcreator.SIPCreatorConfig.<init>(SIPCreatorConfig.java:85)
	at pt.gov.dgarq.roda.sipcreator.SIPCreatorConfig.getInstance(SIPCreatorConfig.java:33)
	at pt.gov.dgarq.roda.sipcreator.Messages.<clinit>(Messages.java:20)
	... 26 more
```

**Comment by luis100** [comment]
RODA-in being remade at https://github.com/keeps/roda-in
RODA API being remade as a REST API
