### ISSUE TITLE
Export CSV failed in mid-stream

### ISSUE THREAD

**Issue by luis100** [keeps/roda#691]
Tested example was exporting a 20000 source objects (transferred resources) list on a ingest job.

The following error appears in catalina.out:

```
11-Nov-2016 12:22:41.273 SEVERE [http-nio-8080-exec-15] org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse An I/O error has occurred while writing a response message entity to the container output 
stream.
 org.glassfish.jersey.server.internal.process.MappableException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
(...)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.roda.core.index.utils.IterableIndexResult$1.next(IterableIndexResult.java:124)
        at org.roda.core.index.utils.IterableIndexResult$1.next(IterableIndexResult.java:115)
        at org.roda.wui.api.v1.utils.ResultsCSVOutputStream.consumeOutputStream(ResultsCSVOutputStream.java:59)
        at org.roda.wui.api.v1.utils.ApiUtils$3.write(ApiUtils.java:205)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:78)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:60)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)
        ... 56 more

```

**Comment by hsilva-keep** [comment]
@luis100 This should not happen & cannot reproduce using Apache Solr Embedded. Nevertheless, improvements were made in order to better log when IndexOutOfBoundsException happens & to return NoSuchElementException (which might be understood by 'for each' statements & so forth).
