### ISSUE TITLE
Possible concurrency problem when scheduling period is too fast

### ISSUE THREAD

**Issue by luis100** [keeps/roda#7]
When scheduling period was 10s, the following error occurred:

```
ERROR 2012-11-21 12:10:20,149 (TaskInstanceDatabaseUtility) SQLException inserting new TaskInstance - Deadlock found when trying to get lock; try restarting transaction
com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
at com.mysql.jdbc.Util.getInstance(Util.java:381)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1045)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3536)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3468)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1957)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2107)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2642)
at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1634)
at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1553)
at pt.gov.dgarq.roda.core.scheduler.TaskInstanceDatabaseUtility.insertTaskInstanceParameter(TaskInstanceDatabaseUtility.java:530)
at pt.gov.dgarq.roda.core.scheduler.TaskInstanceDatabaseUtility.insertTaskInstance(TaskInstanceDatabaseUtility.java:128)
at pt.gov.dgarq.roda.core.scheduler.SchedulerManager.createTaskInstance(SchedulerManager.java:577)
at pt.gov.dgarq.roda.core.scheduler.PluginJob.execute(PluginJob.java:97)
at org.quartz.core.JobRunShell.run(JobRunShell.java:199)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:546)
```

**Comment by luis100** [comment]
Database and scheduling mechanism discontinued in 2.0 version.
