### ISSUE TITLE
PluginHelper.createRiskIfNotExists raises GenericException

### ISSUE THREAD

**Issue by rui-castro** [keeps/roda#714]
## Description

Using method [PluginHelper.createRiskIfNotExists](https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/java/org/roda/core/plugins/plugins/PluginHelper.java#L447) on a risk that doesn't exist works fine; on a risk that already exists (running the same plugin twice) produces the following error:

```
org.roda.core.data.exceptions.GenericException: Error while parsing JSON
	at org.roda.core.data.utils.JsonUtils.getObjectFromJson(JsonUtils.java:144)
	at org.roda.core.data.utils.JsonUtils.getObjectFromJson(JsonUtils.java:130)
	at org.roda.core.model.ModelService.retrieveRisk(ModelService.java:1805)
	at org.roda.core.plugins.plugins.PluginHelper.createRiskIfNotExists(PluginHelper.java:462)
	at org.roda.core.plugins.risks.FileNotCharacterizedRiskAssessmentPlugin.createIncidence(FileNotCharacterizedRiskAssessmentPlugin.java:350)
	at org.roda.core.plugins.risks.FileNotCharacterizedRiskAssessmentPlugin.executeOnFile(FileNotCharacterizedRiskAssessmentPlugin.java:271)
	at org.roda.core.plugins.risks.FileNotCharacterizedRiskAssessmentPlugin.execute(FileNotCharacterizedRiskAssessmentPlugin.java:127)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:49)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:35)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Name is null
 at [Source: {"id":"urn:filenotcharacterized:r1","name":"File(s) not comprehensively characterized","description":"It is essential that all the content ingested in the repository be sufficiently well understood to allow it to be properly managed, preserved and accessed. In practice, this requires metadata describing the content of the files to be created in enough detail.\nFile formats evolve as users and developers identify and incorporate new functionality. New formats, or versions of formats, may introduce file format obsolescence as newer generations of software phase out support for older formats. When software does not provide for backwards compatibility with older file formats, data may become unusable. Both open source and commercial formats are vulnerable to obsolescence: vendors sometimes use planned obsolescence to entice customers to upgrade to new products while open source software communities may withdraw support for older formats if these are no longer generally needed by the community. Obsolescence can also be accidental: both businesses and open source communities can fail.\nFile format obsolescence is therefore a real risk that a repository needs to manage. Having a clear understanding about the file formats that exist in the repository is an essential task to be able the determine the level of risk associated with the repository and devise proper actions to mitigate it. Not knowing your collections in enough technical detail is a risk that should be avoided at all costs.","identifiedOn":1468515641122,"identifiedBy":"Risk automatically detected by the File Not Characterized risk assessment plugin \"org.roda.core.plugins.risks.FileNotCharacterizedRiskAssessmentPlugin\".","category":"Content characterization","notes":"The description of this risk has been partially obtained from the Digital Preservation Handbook (http://handbook.dpconline.org/technical-solutions-and-tools/file-formats-and-standards) published by the Digital Preservation Coalition (DPC).","preMitigationProbability":4,"preMitigationImpact":3,"preMitigationSeverity":12,"preMitigationSeverityLevel":"MODERATE","preMitigationNotes":"If no action is taken there is a high risk that the repository is unware of its contents and therefore unable to assess and mitigate potential obsolescence risks.","postMitigationProbability":0,"postMitigationImpact":0,"postMitigationSeverity":0,"postMitigationSeverityLevel":null,"postMitigationNotes":null,"mitigationStrategy":"Run a content characterization process on the repository content that is not comprehensively characterized.","mitigationOwnerType":null,"mitigationOwner":null,"mitigationRelatedEventIdentifierType":null,"mitigationRelatedEventIdentifierValue":null,"createdOn":1480120907692,"createdBy":"admin","updatedOn":1480120907692,"updatedBy":null,"currentSeverityLevel":"MODERATE"}; line: 1, column: 2412] (through reference chain: org.roda.core.data.v2.risks.Risk["postMitigationSeverityLevel"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:262)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:537)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:518)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797)
	at org.roda.core.data.utils.JsonUtils.getObjectFromJson(JsonUtils.java:142)
	... 20 common frames omitted
Caused by: java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:236)
	at org.roda.core.data.v2.risks.Risk$SEVERITY_LEVEL.valueOf(Risk.java:26)
	at org.roda.core.data.v2.risks.Risk.setPostMitigationSeverityLevel(Risk.java:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:97)
	... 25 common frames omitted
```

### JSON used to create the risk

```json
{
	"id": "urn:filenotcharacterized:r1",
	"name": "File(s) not comprehensively characterized",
	"description": "It is essential that all the content ingested in the repository be sufficiently well understood to allow it to be properly managed, preserved and accessed. In practice, this requires metadata describing the content of the files to be created in enough detail.\nFile formats evolve as users and developers identify and incorporate new functionality. New formats, or versions of formats, may introduce file format obsolescence as newer generations of software phase out support for older formats. When software does not provide for backwards compatibility with older file formats, data may become unusable. Both open source and commercial formats are vulnerable to obsolescence: vendors sometimes use planned obsolescence to entice customers to upgrade to new products while open source software communities may withdraw support for older formats if these are no longer generally needed by the community. Obsolescence can also be accidental: both businesses and open source communities can fail.\nFile format obsolescence is therefore a real risk that a repository needs to manage. Having a clear understanding about the file formats that exist in the repository is an essential task to be able the determine the level of risk associated with the repository and devise proper actions to mitigate it. Not knowing your collections in enough technical detail is a risk that should be avoided at all costs.",
	"identifiedOn": 1468515641122,
	"identifiedBy": "Risk automatically detected by the File Not Characterized risk assessment plugin \"org.roda.core.plugins.risks.FileNotCharacterizedRiskAssessmentPlugin\".",
	"category": "Content characterization",
	"notes": "The description of this risk has been partially obtained from the Digital Preservation Handbook (http://handbook.dpconline.org/technical-solutions-and-tools/file-formats-and-standards) published by the Digital Preservation Coalition (DPC).",
	"preMitigationProbability": 4,
	"preMitigationImpact": 3,
	"preMitigationSeverity": 12,
	"preMitigationSeverityLevel": "MODERATE",
	"preMitigationNotes": "If no action is taken there is a high risk that the repository is unware of its contents and therefore unable to assess and mitigate potential obsolescence risks.",
	"mitigationStrategy": "Run a content characterization process on the repository content that is not comprehensively characterized.",
	"createdOn": 1468515641122,
	"createdBy": "admin"
}
```

### JSON of risk created (~/.roda/data/storage/risk/urn:filenotcharacterized:r1.json)

```json
{
  "id": "urn:filenotcharacterized:r1",
  "name": "File(s) not comprehensively characterized",
  "description": "It is essential that all the content ingested in the repository be sufficiently well understood to allow it to be properly managed, preserved and accessed. In practice, this requires metadata describing the content of the files to be created in enough detail.\nFile formats evolve as users and developers identify and incorporate new functionality. New formats, or versions of formats, may introduce file format obsolescence as newer generations of software phase out support for older formats. When software does not provide for backwards compatibility with older file formats, data may become unusable. Both open source and commercial formats are vulnerable to obsolescence: vendors sometimes use planned obsolescence to entice customers to upgrade to new products while open source software communities may withdraw support for older formats if these are no longer generally needed by the community. Obsolescence can also be accidental: both businesses and open source communities can fail.\nFile format obsolescence is therefore a real risk that a repository needs to manage. Having a clear understanding about the file formats that exist in the repository is an essential task to be able the determine the level of risk associated with the repository and devise proper actions to mitigate it. Not knowing your collections in enough technical detail is a risk that should be avoided at all costs.",
  "identifiedOn": 1468515641122,
  "identifiedBy": "Risk automatically detected by the File Not Characterized risk assessment plugin \"org.roda.core.plugins.risks.FileNotCharacterizedRiskAssessmentPlugin\".",
  "category": "Content characterization",
  "notes": "The description of this risk has been partially obtained from the Digital Preservation Handbook (http://handbook.dpconline.org/technical-solutions-and-tools/file-formats-and-standards) published by the Digital Preservation Coalition (DPC).",
  "preMitigationProbability": 4,
  "preMitigationImpact": 3,
  "preMitigationSeverity": 12,
  "preMitigationSeverityLevel": "MODERATE",
  "preMitigationNotes": "If no action is taken there is a high risk that the repository is unware of its contents and therefore unable to assess and mitigate potential obsolescence risks.",
  "postMitigationProbability": 0,
  "postMitigationImpact": 0,
  "postMitigationSeverity": 0,
  "postMitigationSeverityLevel": null,
  "postMitigationNotes": null,
  "mitigationStrategy": "Run a content characterization process on the repository content that is not comprehensively characterized.",
  "mitigationOwnerType": null,
  "mitigationOwner": null,
  "mitigationRelatedEventIdentifierType": null,
  "mitigationRelatedEventIdentifierValue": null,
  "createdOn": 1480120907692,
  "createdBy": "admin",
  "updatedOn": 1480120907692,
  "updatedBy": null,
  "currentSeverityLevel": "MODERATE"
}
```

**Comment by nunovieira220** [comment]
@rui-castro I cannot reproduce this issue. Merge your branch with mine (or Faria's one) and try again.

**Comment by rui-castro** [comment]
@nunovieira220 you're right. I rebased on lf_dev branch and the problem disappeared.

**Comment by rui-castro** [comment]
This issue is already fixed in [lf_dev](keeps/roda/tree/lf_dev).
