### ISSUE TITLE
Rebuild risk index is failing

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#724]
(At https://github.com/keeps/roda/commit/f5695e83836c320a6f72a4cf1e012857104871b0)

I selected some risks and clicked the start new process button, I used the Rebuild risk index (1.0) workflow and selected "clear indexes". Clicking the button "Create" works but the process fails to reindex.

Outcome details (for each risk):
`Error trying to reindex an unconfigured object class: org.roda.core.data.v2.risks.IndexedRisk`

Relevant log part:

```
2016-12-02 11:17:58,704 [qtp1057260659-146] INFO  o.r.c.p.o.AkkaEmbeddedPluginOrchestrator - Adding job 'RiskIncidenceRemoverPlugin Fri Dec 02 11:17:58 WET 2016' (bb495088-f4cc-431a-88d4-80eb0d0bd14e) to be executed
2016-12-02 11:17:58,704 [qtp1057260659-146] INFO  o.r.c.p.o.AkkaEmbeddedPluginOrchestrator - Success adding job 'RiskIncidenceRemoverPlugin Fri Dec 02 11:17:58 WET 2016' (bb495088-f4cc-431a-88d4-80eb0d0bd14e) to be executed
2016-12-02 11:17:58,704 [JobsSystem-akka.actor.default-dispatcher-437] INFO  o.r.c.p.o.akka.AkkaJobsManager - Will execute job 'bb495088-f4cc-431a-88d4-80eb0d0bd14e' (max: 9| exec: 1| wait: 0)
2016-12-02 11:17:58,705 [JobsSystem-akka.actor.default-dispatcher-54] INFO  o.r.c.p.o.AkkaEmbeddedPluginOrchestrator - Starting Removes old risk incidences (which will be done asynchronously)
2016-12-02 11:17:58,705 [JobsSystem-akka.actor.default-dispatcher-437] DEBUG o.r.c.p.o.akka.AkkaJobStateInfoActor - Starting AkkaJobStateInfoActor router with 9 actors
2016-12-02 11:17:58,705 [JobsSystem-akka.actor.default-dispatcher-54] ERROR o.r.c.p.o.AkkaEmbeddedPluginOrchestrator - Error running plugin on RODA Objects (Risk)
org.roda.core.data.exceptions.NotFoundException: Could not retrieve the Risk
	at org.roda.core.plugins.orchestrate.JobsHelper.getObjectsFromIndex(JobsHelper.java:339)
	at org.roda.core.plugins.orchestrate.JobsHelper.getObjectsFromUUID(JobsHelper.java:317)
	at org.roda.core.plugins.orchestrate.AkkaEmbeddedPluginOrchestrator.runPluginOnObjects(AkkaEmbeddedPluginOrchestrator.java:203)
	at org.roda.core.plugins.orchestrate.akka.AkkaJobActor.runFromList(AkkaJobActor.java:111)
	at org.roda.core.plugins.orchestrate.akka.AkkaJobActor.onReceive(AkkaJobActor.java:82)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2016-12-02 11:17:58,706 [JobsSystem-akka.actor.default-dispatcher-437] INFO  o.r.c.p.o.akka.AkkaJobStateInfoActor - Setting job 'RiskIncidenceRemoverPlugin Fri Dec 02 11:17:58 WET 2016' (bb495088-f4cc-431a-88d4-80eb0d0bd14e) state to STARTED. Details: NO DETAILS
2016-12-02 11:17:58,711 [JobsSystem-akka.actor.default-dispatcher-437] INFO  o.r.c.p.o.akka.AkkaJobStateInfoActor - Setting job 'RiskIncidenceRemoverPlugin Fri Dec 02 11:17:58 WET 2016' (bb495088-f4cc-431a-88d4-80eb0d0bd14e) state to FAILED_TO_COMPLETE. Details: org.roda.core.data.exceptions.NotFoundException: Could not retrieve the Risk
2016-12-02 11:17:58,715 [JobsSystem-akka.actor.default-dispatcher-54] INFO  o.r.c.p.o.akka.AkkaJobsManager - The end for job 'bb495088-f4cc-431a-88d4-80eb0d0bd14e' (max: 9| exec: 0| wait: 0)
```

**Comment by nunovieira220** [comment]
Solved on b03fdb28c4fecc5c8d6497c6e53a75f991ddd385
