### ISSUE TITLE
Digital signature should report failure when no keystore found

### ISSUE THREAD

**Issue by luis100** [keeps/roda#725]
Plugin reported success but log gave error:

```
2016-12-02 16:38:30,996 [JobsSystem-akka.actor.default-dispatcher-41] ERROR o.r.c.p.p.c.DigitalSignatureDIPPluginUtils - Cannot load keystore /home/lfaria/.roda/config/certificates/keystore.jks
java.io.FileNotFoundException: /home/lfaria/.roda/config/certificates/keystore.jks (Ficheiro ou directoria inexistente)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.roda.core.plugins.plugins.characterization.DigitalSignatureDIPPluginUtils.addDetachedSignature(DigitalSignatureDIPPluginUtils.java:119)
	at org.roda.core.plugins.plugins.characterization.DigitalSignatureDIPPlugin.addDIPFileSignature(DigitalSignatureDIPPlugin.java:381)
	at org.roda.core.plugins.plugins.characterization.DigitalSignatureDIPPlugin.manageFileSigning(DigitalSignatureDIPPlugin.java:362)
	at org.roda.core.plugins.plugins.characterization.DigitalSignatureDIPPlugin.executeOnFile(DigitalSignatureDIPPlugin.java:307)
	at org.roda.core.plugins.plugins.characterization.DigitalSignatureDIPPlugin.execute(DigitalSignatureDIPPlugin.java:121)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:49)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:35)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by nunovieira220** [comment]
Solved on d3fdea9ea6423d3f1324eb3d49e6bc07a641807e
