### ISSUE TITLE
Error loading "ConfigurableIngestPlugin"

### ISSUE THREAD

**Issue by luis100** [keeps/roda#771]
```
2017-01-18 13:55:53,426 [main] ERROR org.roda.core.plugins.PluginManager - Unable to instantiate plugin 'org.roda.core.plugins.plugins.ingest.ConfigurableIngestPlugin'
java.lang.NullPointerException: null
	at org.roda.core.plugins.plugins.ingest.ConfigurableIngestPlugin.loadMap(ConfigurableIngestPlugin.java:111)
	at org.roda.core.plugins.plugins.ingest.ConfigurableIngestPlugin.getParameters(ConfigurableIngestPlugin.java:52)
	at org.roda.core.plugins.PluginManager.getPluginInfo(PluginManager.java:269)
	at org.roda.core.plugins.PluginManager.getPluginInfo(PluginManager.java:223)
	at org.roda.core.plugins.PluginManager.processAndCachePluginInformation(PluginManager.java:457)
	at org.roda.core.plugins.PluginManager.loadInternalPlugins(PluginManager.java:410)
	at org.roda.core.plugins.PluginManager.loadPlugins(PluginManager.java:283)
	at org.roda.core.plugins.PluginManager.<init>(PluginManager.java:256)
	at org.roda.core.plugins.PluginManager.getDefaultPluginManager(PluginManager.java:101)
	at org.roda.core.RodaCoreFactory.instantiatePluginManager(RodaCoreFactory.java:573)
	at org.roda.core.RodaCoreFactory.instantiate(RodaCoreFactory.java:322)
	at org.roda.core.RodaCoreFactory.instantiateMaster(RodaCoreFactory.java:231)
	at org.roda.core.RodaCoreFactory.instantiate(RodaCoreFactory.java:220)
	at org.roda.wui.servlets.RodaWuiServlet.init(RodaWuiServlet.java:27)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:534)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:346)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:786)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:541)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:162)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:740)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:632)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:1054)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:836)
	at com.google.gwt.dev.DevMode.main(DevMode.java:413)

```

**Comment by hsilva-keep** [comment]
Solved since 366f6c0ff37eb876bdffe41b893b4d7adec1f58b.
