### ISSUE TITLE
RODA completely crashes because plugin execution throws an error above Exception (e.g. java.lang.NoSuchMethodError)

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#780]
2017-01-20 17:50:00,354 [ ] ERROR akka.actor.ActorSystemImpl - Uncaught error from thread [JobsSystem-io-2-dispatcher-57] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoSuchMethodError: org.roda.core.plugins.plugins.PluginHelper.transformLitesIntoObjects(Lorg/roda/core/model/ModelService;Lorg/roda/core/index/IndexService;Lorg/roda/core/plugins/Plugin;Lorg/roda/core/data/v2/jobs/Report;Lorg/roda/core/plugins/orchestrate/JobPluginInfo;Ljava/util/List;)Ljava/util/List;
        at org.roda.core.plugins.plugins.characterization.VeraPDFPlugin.execute(VeraPDFPlugin.java:157)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:58)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:39)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by hsilva-keep** [comment]
Solved since 750685b507783aa543fc2955067c13396d3a576f.
