### ISSUE TITLE
Many error on migrating PreservationMetadata to version 2

### ISSUE THREAD

**Issue by luis100** [keeps/roda#855]
The error below happens many times on the log. Nevertheless, the migration ends with success.

```
2017-04-10 18:24:28,009 [main] ERROR o.r.c.m.m.PreservationMetadataFileToVersion2 - Could not migrate preservation metadata file aip/8e55024e-d6bb-4ed3-aa07-60ec109a7f5d/representations/uuid-821A0669-35CE-419E-8961-EB0BB35D9AD7/metadata/preservation/urn:roda:premis:file:CE2010054NL.toc.xml.xml
org.roda.core.data.exceptions.AlreadyExistsException: Cannot copy because target path already exists: /home/lfaria/.roda/data/storage/aip/8e55024e-d6bb-4ed3-aa07-60ec109a7f5d/representations/uuid-821A0669-35CE-419E-8961-EB0BB35D9AD7/metadata/preservation/urn:roda:premis:file:CE2010054NL.toc.xml.xml
	at org.roda.core.storage.fs.FSUtils.move(FSUtils.java:132)
	at org.roda.core.storage.fs.FileStorageService.move(FileStorageService.java:446)
	at org.roda.core.migration.model.PreservationMetadataFileToVersion2.migrate(PreservationMetadataFileToVersion2.java:118)
	at org.roda.core.migration.model.PreservationMetadataFileToVersion2.migrate(PreservationMetadataFileToVersion2.java:67)
	at org.roda.core.migration.MigrationManager.performModelMigrations(MigrationManager.java:219)
	at org.roda.core.RodaCoreFactory.mainMasterTasks(RodaCoreFactory.java:1527)
	at org.roda.core.RodaCoreFactory.main(RodaCoreFactory.java:1551)
2017-04-10 18:24:28,243 [main] WARN  o.r.c.m.m.PreservationMetadataFileToVersion2 - Could not find representations
2017-04-10 18:24:28,243 [main] INFO  o.r.core.migration.MigrationManager - Migrated with success to version 2
2017-04-10 18:24:28,243 [main] INFO  o.r.core.migration.MigrationManager - Done migrating class 'org.roda.core.data.v2.ip.metadata.PreservationMetadata'
```

**Comment by luis100** [comment]
This may be because some of the events were created with new code and are on the right place already. The migration script should detect such a case and skip the move.

**Comment by hsilva-keep** [comment]
Well...I'll try to take a look at it until the end of the morning...

**Comment by hsilva-keep** [comment]
@luis100 well, this is not a problem of the migration code, because these errors only happen when one decides to skip the migration task & starts using the repository, ending up with premis files that have the two forms (the older/wrong one & the new/right one).

**Comment by luis100** [comment]
@hsilva-keep I did not skip the migration task. I simply installed the new version and executed the migration, the errors happen while the migration is executing.

**Comment by hsilva-keep** [comment]
@luis100 I find hard to believe. I mean, without using the repository (with the new code), how could the files be generated with the new name format (in order to happen, during the migration, the AlreadyExistsException)?

**Comment by luis100** [comment]
Did the new code exist without the migration check being active?

**Comment by hsilva-keep** [comment]
No. The code (new way to name PREMIS objects & migration) is contained in a single commit (3c8950f9130cb807b61c673fdb5952d0ffcf4f41).

**Comment by luis100** [comment]
Have you tested the migration? Did it not give the same errors?

**Comment by hsilva-keep** [comment]
Yes. I don't have a big corpora, but I've tested two scenarios:
* data/storage/aip/ only with premis files in the old name form (i.e. without the name of the data file)
```bash
$> find data/storage/aip/ | egrep "premis:file"
data/storage/aip/bf34344c-2e3e-46d9-8cbd-1b55cf47ad19/representations/rep1/metadata/preservation/urn:roda:premis:file:a252c729-9220-3243-ab2f-8a53044de3fa.xml
data/storage/aip/ee1b2aa0-d336-418b-ad1d-1aa659fb97a8/representations/rep1/metadata/preservation/urn:roda:premis:file:bb485a90-61af-3eb4-a20d-02f75cf72d71.xml
data/storage/aip/ee1b2aa0-d336-418b-ad1d-1aa659fb97a8/representations/rep1/metadata/preservation/urn:roda:premis:file:24ed307c-5e29-3a53-a921-9ae126ad6810.xml
data/storage/aip/5408d7a3-9efd-4616-9609-7f335d976489/representations/rep1/metadata/preservation/urn:roda:premis:file:c1febaf8-ca4d-37da-82f4-3d0881b652b8.xml
data/storage/aip/b6a926c1-84a8-4617-a437-fe9cf2b3ee39/representations/rep2/metadata/preservation/urn:roda:premis:file:82ed6ce8-f91f-303c-9802-a694328ca4ae.xml
data/storage/aip/b6a926c1-84a8-4617-a437-fe9cf2b3ee39/representations/rep1/metadata/preservation/urn:roda:premis:file:0b1f6d19-71e9-3abd-b7c2-dcc3c7935bf1.xml
```
* data/storage/aip/ with files in the older & new name form
```bash
$> find data/storage/aip | egrep "premis:file"
data/storage/aip/bf34344c-2e3e-46d9-8cbd-1b55cf47ad19/representations/rep1/metadata/preservation/urn:roda:premis:file:a252c729-9220-3243-ab2f-8a53044de3fa.xml
data/storage/aip/ee1b2aa0-d336-418b-ad1d-1aa659fb97a8/representations/rep1/metadata/preservation/urn:roda:premis:file:bb485a90-61af-3eb4-a20d-02f75cf72d71.xml
data/storage/aip/ee1b2aa0-d336-418b-ad1d-1aa659fb97a8/representations/rep1/metadata/preservation/urn:roda:premis:file:24ed307c-5e29-3a53-a921-9ae126ad6810.xml
data/storage/aip/5408d7a3-9efd-4616-9609-7f335d976489/representations/rep1/metadata/preservation/urn:roda:premis:file:c1febaf8-ca4d-37da-82f4-3d0881b652b8.xml
data/storage/aip/e16a0bc6-9705-492a-a953-65dc575051e6/representations/rep1/metadata/preservation/urn:roda:premis:file:20151008_asus.txt.xml
data/storage/aip/b6a926c1-84a8-4617-a437-fe9cf2b3ee39/representations/rep2/metadata/preservation/urn:roda:premis:file:82ed6ce8-f91f-303c-9802-a694328ca4ae.xml
data/storage/aip/b6a926c1-84a8-4617-a437-fe9cf2b3ee39/representations/rep1/metadata/preservation/urn:roda:premis:file:0b1f6d19-71e9-3abd-b7c2-dcc3c7935bf1.xml
```

And just in the second scenario the error occurs.
