### ISSUE TITLE
Move debug error on an expected authorization denied

### ISSUE THREAD

**Issue by luis100** [keeps/roda#951]
When trying to move a AIP with a user that has no permission to do so a error is shown in the log, but this is an expected behavior and should not create such an error log.

```
2017-04-27 17:18:18,016 [http-apr-8080-exec-5] ERROR o.r.w.s.browse.BrowserServiceImpl - Unexpected error
org.roda.core.data.exceptions.AuthorizationDeniedException: The user 'test2' does not have permissions to UPDATE
	at org.roda.core.common.UserUtility.checkAIPPermissions(UserUtility.java:200)
	at org.roda.core.common.UserUtility.checkAIPPermissions(UserUtility.java:334)
	at org.roda.wui.api.controllers.Browser.moveAIPInHierarchy(Browser.java:1030)
	at org.roda.wui.server.browse.BrowserServiceImpl.moveAIPInHierarchy(BrowserServiceImpl.java:327)

```

**Comment by nunovieira220** [comment]
Solved on 7356b5498713e92cdd27da5c6085817d260bc85c
