### ISSUE TITLE
Error ingesting SIPs with a classification plan

### ISSUE THREAD

**Issue by luis100** [keeps/roda#980]
Steps to reproduce:
1. Use a corpora that has a complex folder structure
2. With RODA-in create SIPs using the "One classification scheme from folder structure" option
3. Export all SIPs including hierarchy and ingest them in RODA all together

The following error was found on the final stages of ingesting:

```
2017-05-09 22:56:12,225 [JobsSystem-io-2-dispatcher-232] DEBUG o.roda.core.index.IndexModelObserver - Reindexing aip 067c5fdb-7e85-4ce9-98ad-1b24da4869a2 descendant 1a1d4581-2f66-4859-92fd-e53edcf2e67a
2017-05-09 22:56:12,226 [JobsSystem-io-2-dispatcher-232] ERROR o.roda.core.index.IndexModelObserver - Error indexing moved AIP 067c5fdb-7e85-4ce9-98ad-1b24da4869a2 from 655e6615-92df-4669-a36a-09fdbc1bd729 to 7e8598e1-13ee-4ecc-9f19-c52e2f26c7a4
org.roda.core.data.exceptions.NotFoundException: Cannot find file or directory at /home/lfaria/.roda/data/storage/aip/1a1d4581-2f66-4859-92fd-e53edcf2e67a/aip.json
	at org.roda.core.storage.fs.FSUtils.convertPathToResource(FSUtils.java:623)
	at org.roda.core.storage.fs.FileStorageService.getBinary(FileStorageService.java:403)
	at org.roda.core.model.utils.ResourceParseUtils.getAIPMetadata(ResourceParseUtils.java:366)
	at org.roda.core.model.utils.ResourceParseUtils.getAIPMetadata(ResourceParseUtils.java:353)
	at org.roda.core.model.ModelService.retrieveAIP(ModelService.java:235)
	at org.roda.core.index.IndexModelObserver$1.run(IndexModelObserver.java:511)
	at org.roda.core.index.IndexModelObserver$1.run(IndexModelObserver.java:1)
	at org.roda.core.index.utils.SolrUtils.execute(SolrUtils.java:2718)
	at org.roda.core.index.IndexModelObserver.aipMoved(IndexModelObserver.java:501)
	at org.roda.core.model.ModelObservable.notifyAipMoved(ModelObservable.java:61)
	at org.roda.core.model.ModelService.moveAIP(ModelService.java:471)
	at org.roda.core.plugins.plugins.PluginHelper.lambda$5(PluginHelper.java:1108)
	at org.roda.core.index.utils.SolrUtils.execute(SolrUtils.java:2718)
	at org.roda.core.index.IndexService.execute(IndexService.java:506)
	at org.roda.core.plugins.plugins.PluginHelper.moveChildrenAIPsAndDelete(PluginHelper.java:1106)
	at org.roda.core.plugins.plugins.PluginHelper.fixParents(PluginHelper.java:1065)
	at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.afterAllExecute(DefaultIngestPlugin.java:289)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginAfterAllExecuteIsReady(AkkaWorkerActor.java:71)
	at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:41)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by luis100** [comment]
Log level changed from error to debug
